### ISSUE TITLE
BatchSize greater than 1 does not work

### ISSUE THREAD

**Issue by shagunsodhani** [mbchang/crl#2]
Hello!

I am running experiments related to ArithLang example. I have managed to setup the code and do a complete run of the model with `bsize` (batchsize) set to 1 but it seems that the environment does not support a larger than 1 batch size. I want to check if this is indeed the case (and that I am not doing any mistake while running the code) and if you are planning to release the code with support for larger batch size as well.

**Comment by mbchang** [comment]
Hi! Thank you for your question. The reason why the batch size is 1 is because we are training the controller on-policy. From the controller's point of view, it is solving an reinforcement learning problem where it first collects a set of transitions, puts these transitions in a replay buffer, and then updates its parameters by optimizing the policy gradient objective on the transitions in the replay buffer. With a single thread, it collects the transitions with a batch size of 1 just like the typical RL formulation. The policy gradient update step is batched. So yes, it is correct that with the current code the batch size must be 1. For the ArithLang example, the inputs change in length (for example, you could have an input of "3+4*7-2" at timestep t, and then 3+8-2 at timestep t+1 (modulo 10)). Because different math expressions could be different lengths within a batch, one would need to keep track of their relative lengths. It is a bit messy to keep track of this, so I went with the cleaner version of just having everything be a batch size of 1. If you are interested in submitting a pull request to support larger batch size, that would be welcome and appreciated!

**Comment by shagunsodhani** [comment]
Hey @mbchang Thanks for the reply. The complexity was a concern for me as well and that is why I first wanted to check with you. I am glad to know that you are open to accepting PRs. I would send one if I end up implementing the support for larger batch size :)
